version: "3.4"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prisma
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
